### ISSUE TITLE
Jolly Mec - Problem with temperature value

### ISSUE THREAD

**Issue by Slavitacus** [securechicken/homebridge-micronova-agua-iot-stove#1]
## Environment and Input

|Item|Your information|
|---|---|
|**Homebridge Version**|1.3.1|
|**Plugin version**|v0.0.1-alpha.2|
|**Stove brand/mobile app name**|Jolly Mec|
|**iOS version**|NA|

### Expected function and references
I have problems with the temperature setting, i can't set up to 20, and i have this message :
`[3/3/2021, 7:59:14 AM] [homebridge-micronova-agua-iot-stove] This plugin generated a warning from the characteristic 'Current Temperature': characteristic was supplied illegal value: number 23 exceeded maximum of 20. See https://git.io/JtMGR for more info.`
### Steps to Reproduce

1.
2. ...

### Possible Implementation

Thank you very much for all the work you do on this pluging, its really awesome ! 👍

**Comment by securechicken** [comment]
Hi @Slavitacus , thanks for reporting,

Did you manage to do it with py-agua-iot without issue?

Could you change any other setting/state like powering ON/OFF or changing stove flame power with HomeKit rotation speed?

Could you please enable debug mode with Homebridge (see Homebridge documentation), and paste every line of the plugin logs (relevant lines start with [your stove name]) from Homebridge, except the plugin init line (first line) where your password is mentioned of course.

**Comment by Slavitacus** [comment]
hello @securechicken, I'll check all this points this week-end and come back to you. Thks

**Comment by Slavitacus** [comment]
hi @securechicken , I'm sorry, but my knowledge is limited, I can't find how to enable debug mode on my Hombridge...
BTW, sometime the pluging works (exept the temperature value), sometime not. When it works, I can powering ON/OFF and change the speed.

**Comment by securechicken** [comment]
Top right corner of Homebridge Web UI, click the 3 dots, then "Homebridge Settings" in the menu that appeared.
You will have a screen with an ON/OFF slider called "Homebridge Debug Mode". 

![Homebirdge settings UI example](https://github.com/oznu/homebridge-config-ui-x/raw/master/screenshots/homebridge-config-ui-x-docker-settings.png)

Put that ON, then restart Homebridge with the "POWER ON" button on top right corner.

You will have a lot of messages available in Homebridge Web UI log panel, copy/paste the most of if, including when your issue happens, then filter to keep the lines that start with your stove name between `[ ]` only (other lines starting with another name are debug messages from others plugins I'm not interested in).

Without such messages, there is unfortunately no way I can try to find and fix the root of an issue, as I don't have the specific stove model you use at hand and cannot reproduce.

**Comment by Slavitacus** [comment]
Okay, Thanks taking time to explain !
```
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p2_day_thursday_set=1
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p1_temperature_set=42
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: canalization_2_set=0
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p3_day_sunday_set=0
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p2_stop_set=144
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p3_day_tuesday_set=1
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: calendar_day_week_set=6
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: temp_gas_flue_get=0
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: status_managed_get=4
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p2_day_friday_set=1
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p4_day_friday_set=1
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p1_day_thursday_set=1
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p2_temperature_set=34
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p4_day_monday_set=1
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p4_stop_set=144
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p4_day_tuesday_set=1
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p3_day_wednesday_set=1
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: calendar_day_set=6
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p3_temperature_set=42
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p4_day_thursday_set=1
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: canalization_1_set=0
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p1_start_set=40
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult setting raw value: chrono_p1_stop_set=144
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _waitForRegistersDataReadJobResult updated stove registers from API
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _getStoveRegister status_get: {"_v":0,"reg_type":"GET","offset":33,"formula":"#","formula_inverse":"#","format_string":"{0}","set_min":0,"set_max":50,"mask":65535,"_offv":0}
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _getStoveRegisterValueFromCache status_get => 0
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _updateCharacteristicsValues Active: 0 => 0, (ERR: null)
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _updateCharacteristicsValues CurrentHeaterCoolerState: 0 => 0, (ERR: null)
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _getStoveRegister temp_air_get: {"_v":37,"reg_type":"GET","offset":20,"formula":"#/2","formula_inverse":"#*2","format_string":"{0}°C","set_min":7,"set_max":40,"mask":65535}
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _getStoveRegisterValueFromCache temp_air_get => 18.5
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _updateCharacteristicsValues CurrentTemperature: 18.5, (ERR: null)
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _getStoveRegister temp_air_set: {"_v":42,"reg_type":"SET","offset":32875,"formula":"#/2","formula_inverse":"#*2","format_string":"{0}°C","set_min":7,"set_max":40,"mask":65535}
[3/6/2021, 4:12:49 PM] [Poêle Chalet Taroko] _getStoveRegisterValueFromCache temp_air_set => 21
[3/6/2021, 4:12:50 PM] [homebridge-micronova-agua-iot-stove] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 21 exceeded maximum of 20. See https://git.io/JtMGR for more info.
[3/6/2021, 4:12:50 PM] [homebridge-micronova-agua-iot-stove] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2118:14)
    at HeatingThresholdTemperature.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1365:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at /homebridge/node_modules/homebridge-micronova-agua-iot-stove/index.js:951:25
    at /homebridge/node_modules/homebridge-micronova-agua-iot-stove/index.js:851:6
    at HeaterCoolerMicronovaAguaIOTStove._getStoveRegister (/homebridge/node_modules/homebridge-micronova-agua-iot-stove/index.js:778:5)
    at HeaterCoolerMicronovaAguaIOTStove._getStoveRegisterValueFromCache (/homebridge/node_modules/homebridge-micronova-agua-iot-stove/index.js:847:9)
    at /homebridge/node_modules/homebridge-micronova-agua-iot-stove/index.js:949:10
    at /homebridge/node_modules/homebridge-micronova-agua-iot-stove/index.js:757:9
[3/6/2021, 4:12:50 PM] [Poêle Chalet Taroko] _updateCharacteristicsValues HeatingThresholdTemperature: 21, (ERR: null)
[3/6/2021, 4:12:50 PM] [Poêle Chalet Taroko] _getStoveRegister real_power_get: {"_v":1,"reg_type":"GET","offset":69,"formula":"#","formula_inverse":"#","format_string":"{0}","set_min":0,"set_max":5,"mask":255}
[3/6/2021, 4:12:50 PM] [Poêle Chalet Taroko] _getStoveRegisterValueFromCache real_power_get => 1
[3/6/2021, 4:12:50 PM] [Poêle Chalet Taroko] _updateCharacteristicsValues RotationSpeed: 1, (ERR: null)
[3/6/2021, 4:12:50 PM] [Homebridge UI] Starting terminal session
```

is it enough? Do you need something else?

**Comment by securechicken** [comment]
Thanks, perfect.
I edited your post to keep the relevant part of the logs only, as well as remove any sensitive data (the authorization token), and format logs lines as raw text.

What is happening is that the target heating temperature of the stove do not fit in temperature boundaries that are specified by the stove. This seems to be due to the fact that the boundaries values are given as final values, where they are expected to be given as values to be calculated by the plugin - meaning a calculation formula provided by the stove is applied by the plugin. Max given temperature boundary is 40°, and formula is `/2`, so the final result calculated by plugin is 20° (40/2). 

```
"_v":42,"reg_type":"SET","offset":32875,"formula":"#/2","formula_inverse":"#*2","format_string":"{0}°C","set_min":7,"set_max":40,"mask":65535}
```

I’ll fix this in next alpha, but I need to check if the way boundaries values are provided is common to every stove, or specific to your brand. If it’s specific it will require more time to fix. Anyway thanks for reporting this, very useful.

**Comment by securechicken** [comment]
@Slavitacus, please check if v0.0.1-alpha.3 is solving your issue :)
Regards.

**Comment by Slavitacus** [comment]
Hi @securechicken , I'll check this ! Thank you

**Comment by Slavitacus** [comment]
So, yeah, it works Thanks you very much !!! 
But I have to restart 3-4 times Homebridge to make it works well, I often have this message:
`[3/7/2021, 7:46:37 PM] [Poêle Chalet Taroko] init could not register app with API: network timeout at: https://jollymec.agua-iot.com/appSignup`

**Comment by securechicken** [comment]
Glad it worked!
For traceability and readability reasons, we never discuss and handle different bugs or problems in the same issue within GitHub: another one with updated info should be opened if your other issue persists - it is related to a network timeout, which in the plugin case means that the Micronova server did not answer within 5s (very long delay from a network standpoint), or that your Internet connection was slow/interrupted.
